resources:
 containers:
  - container: app    
    image: devopstestcr1.azurecr.io/server:latest
    endpoint: devopstest
trigger: none
jobs:
  - job: testImage
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'devopstest'
        command: 'login'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'docker pull devopstestcr1.azurecr.io/server:latest'
      continueOnError: true  
  - job: pullImage
    dependsOn: testImage
    condition: failed()
    steps:
      - template: jobs/build.yaml
  - job: test
    container: app
    steps:
      - template: jobs/build.yaml