trigger: none
steps:
- task: Docker@2
  inputs:
    containerRegistry: 'devopstest'
    command: 'login'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'docker pull devopstestcr1.azurecr.io/server:latest'
  continueOnError: true  
- template: ../jobs/build.yaml
  condition: always()
  