resources:
 containers:
  - container: app    
    image: devopstestcr1.azurecr.io/server:latest
    endpoint: devopstest
trigger: none
jobs:
  - job: testImage
    displayName: Check Image Exists
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'devopstest'
        command: 'login'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'docker pull devopstestcr1.azurecr.io/server:latest'
      continueOnError: true  
  - job: buildImage  
    displayName: Build Image
    dependsOn: testImage
    condition: failed()
    steps:
      - template: jobs/build.yaml
  - job: runTest
    displayName: Run Test
    dependsOn: buildImage
    condition: succeededOrFailed()
    container: app    
    steps:
      - template: jobs/build.yaml