steps:
- task: Docker@2
  inputs:
    containerRegistry: 'devopstest'
    command: 'login'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'docker pull devopstestcr1.azurecr.io/server:latest'
- task: Docker@2
  inputs:
    containerRegistry: 'devopstest'
    repository: 'server'
    command: 'buildAndPush'
    Dockerfile: 'server/dockerfile'
    tags: |
      $(Build.SourceVersion)
      latest
