resources:
 containers:
  - container: node
    image: node:latest
  - container: app
    image: devopstestcr1.azurecr.io/server:latest
jobs:
- job: test
  container: node  
  dependsOn: startContainer
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        npm i jest
        npm i axios
        npx jest server/test/all.test.js --outputFile result.json
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/result.json'
      testRunTitle: 'test'
  


  