resources:
 containers:
  - container: app
    type: ACR
    image: devopstestcr1.azurecr.io/server:latest
    azureSubscription: Microsoft Azure Sponsorship
    resourceGroup: rg-devops-dev-001
    registry: devopstestcr1
    repository: server
jobs:
- job: test
  container: app  
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |      
        npm i jest
        npm i axios
        npx jest server/test/all.test.js --outputFile result.json
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/result.json'
      testRunTitle: 'test'
  


  