jobs:
- job: startContainer
  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'devopstest'
      command: 'login'
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        docker run --name server -d --rm -p 8000:8000 devopstestcr1.azurecr.io/server:latest
- job: test
  container: node:latest
  dependsOn: startContainer
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        npm i -g jest
        jest server/test/all.test.js --outputFile result.json
        docker stop server
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/result.json'
      testRunTitle: 'test'
  


  